name: CI

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed, opened, synchronize, reopened ]
  issue_comment:
    types: [created]
    if: contains(github.event.comment.body, 'digger')
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux]

    steps:
      - name: digger run
        uses: diggerhq/digger@v0.1.31
        with:
          setup-aws: true
          aws-role-to-assume: arn:aws:iam::426222967960:role/aws-terraform-pipeline-test
          aws-region: eu-north-1
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
